name: Delete Branch After Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Delete Branch
        run: |
          git fetch --prune
          git branch -D ${{ github.event.pull_request.head.ref }}
          git push origin :${{ github.event.pull_request.head.ref }}

      - name: Send Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub
          DISCORD_AVATAR: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        with:
          args: "The branch '${{ github.event.pull_request.head.ref }}' has been merged and deleted."
